### ISSUE TITLE
Improve Responsive Design for Brickwork Store Pages Images

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#10]
• improve the responsive design so the store images can look better on all devices
• determine the specs and send to Chuck
• publish documentation

**Comment by juanmriosv** [comment]
**Transfered to BRICKWORK repository**
I Tried to close it, was not able

**Comment by c21hornak** [comment]
https://github.com/Century21Stores/BRICKWORK/issues/1
