### ISSUE TITLE
Assets Image Compression

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/SPECIAL#11]
**Sample of the Issue:**
![screen shot 2017-02-17 at 9 53 36 am](https://cloud.githubusercontent.com/assets/16789090/23070503/3bc89486-f4f9-11e6-89d5-684a81a6447d.png)
![screen shot 2017-02-17 at 10 00 00 am](https://cloud.githubusercontent.com/assets/16789090/23070504/3bcdba9c-f4f9-11e6-8874-e4119d946b01.png)

**Ideal setting found when saving for web**
![screen shot 2017-02-17 at 10 07 24 am](https://cloud.githubusercontent.com/assets/16789090/23070485/2ebc63b2-f4f9-11e6-99b5-06978dabf6f8.png)

**Comment by lstaab** [comment]
Noted to watch and adjust. Thanks.
