### ISSUE TITLE
Dashboard 2016 Jan W03 and W04 not showing data

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/SPECIAL#12]

**Comment by juanmriosv** [comment]
January W03 and W04 now showing
[https://docs.google.com/spreadsheets/d/1-XCAlwI3-QUHQymfewYM0qfC4rENDuK5XaSoLeEEuyo/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1-XCAlwI3-QUHQymfewYM0qfC4rENDuK5XaSoLeEEuyo/edit?usp=sharing
)

**Comment by c21hornak** [comment]
This is fixed. Closing.
