### ISSUE TITLE
Add Signature Required Verbiage with Justuno

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/SPECIAL#13]
Elisabeth wants to know if it’s possible to use Justuno in the checkout to detect when an order total is $500 or greater, and if so, display a message that a signature is required from the courier in order to receive the shipment.
This is just a way to notify the guest about something without WebLinc having to do any development.

**Comment by juanmriosv** [comment]
@c21hornak Yes it is possible.

I place a sample on staging. When the price is greater than $140 (just for testing purposes), the message will display.
Also, I can place banners.


![screen shot 2017-03-08 at 9 30 43 am](https://cloud.githubusercontent.com/assets/16789090/23707927/22c55b20-03e2-11e7-9d5b-d2f205161268.png)

**Comment by c21hornak** [comment]
@juanmriosv prototype is approved and the official copy from Emily is this:
"Signature required to receive orders of $500 or more."

See Workfront request: https://c21.attask-ondemand.com/issue/view?ID=5900c2e700023871110df61fcc5f2a4e

Please proceed to prepare the prototype for QA testing on STAGING.

**Comment by c21hornak** [comment]
@juanmriosv I just added this to the top of your iCloud today

**Comment by juanmriosv** [comment]
@c21hornak All done Michael

**Comment by c21hornak** [comment]
@juanmriosv I think I forgot about this back in May... Can this Justuno code please be added back to STAGING with the condition that it displays when the subtotal is $500 or greater?

![signature-required-500](https://user-images.githubusercontent.com/19403001/34413227-f9386282-ebaf-11e7-96b6-7e98b1198f05.png)

**Comment by ashahinC21** [comment]
Closing this issue - moving to Wrike.
