### ISSUE TITLE
Guest Service Orders Error Survey Google Doc v1.0

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/SPECIAL#136]
**Requestor:** @c21hornak , Katy Canales

**History:** Currently, customer service has an existing survey, in physical paper form, that it is filled by agents. 
 
**Issue:**  There is not easy way to communicate the results of this survey to Web Production.

> ### **Solution to implement:**  

> **Phase 1:** Create an online form (similar to the password request form) that customer service will fill out. Once this is fill out, all the info will get populated into a spread sheet that web production can manipulate as we wish.

> **Phase 2:** TBD: how do we manipulate the spreadsheet

**Comment by juanmriosv** [comment]
**Form:**
https://docs.google.com/forms/d/e/1FAIpQLSfEKH9VUIZU_HRbFU3jRpLcro3Lu9ao1hOa4A8HEOdEAyM0nA/viewform

**Comment by c21hornak** [comment]
Let's call whatever we deliver today v1.0 (internally, so we can keep track of every time we do work to modify the survey)

**Comment by juanmriosv** [comment]
@c21hornak sounds good.
