### ISSUE TITLE
Make Search "Forget" J&R

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#15]
Request from Elisabeth on 1/4/17: Suppress J&R from appearing as a search suggestion.

We should also make sure that search term returns 0 results.

![unknown](https://cloud.githubusercontent.com/assets/19403001/23903703/cc6ed738-089b-11e7-99c4-4d33ae3cb553.png)

**Comment by c21hornak** [comment]
Update from Adena 1/5/17: The reason results are still coming up is because the products found here are still showing J&R Express as the Department name. That should be removed.
![unknown](https://cloud.githubusercontent.com/assets/19403001/24054197/c27ce4d6-0b11-11e7-8c8c-c72021775279.png)

**Comment by c21hornak** [comment]
Update 2/28/17: Adena to work with Andrea to get the department updated in E1

From: "Goldis, Adena" <agoldis@c21stores.com>
Date: Tuesday, February 28, 2017 at 5:44 PM
To: Michael Hornak <mhornak@c21stores.com>
Subject: Re: J&R

I double checked with him first. He said it does in the nightly feed.

Thanks,
Adena

Description: Anneka G:MARKETING CAMPAIGNS:email signature:email_logo_red_2.png
 
Adena Goldis
UX Manager, eCommerce
P: 201.348.2252 X 7882
C: 609.706.1889
E: agoldis@C21STORES.COM
HDC | 21 CENTURY WAY 
SECAUCUS, NJ 07094

Description: Anneka G:GRAPHIC ASSETS:Corporate logos and fonts:Century 21:Century_21_Website[1]_small.png



From: "Hornak, Michael" <mhornak@c21stores.com>
Date: Tuesday, February 28, 2017 at 4:43 PM
To: a g <agoldis@c21stores.com>
Subject: Re: J&R

Might be one of those things that doesn’t get updated in ME? Loop in Noriel if necessary.

From: "Goldis, Adena" <agoldis@c21stores.com>
Date: Tuesday, February 28, 2017 at 4:42 PM
To: Michael Hornak <mhornak@c21stores.com>
Subject: Re: J&R

The buyers would need to change the MHL attribute in E1, so it can feed into ME to then be updated in mass.
Andrea thought the buyers already did that, but she’ll follow up.

Thanks,
Adena

**Comment by c21hornak** [comment]
From: "Goldis, Adena" <agoldis@c21stores.com>
Date: Thursday, March 9, 2017 at 10:32 AM
To: Michael Hornak <mhornak@c21stores.com>
Subject: Re: Make Search "Forget" J&R?

Update from Andrea: looks like the attributes weren’t changed as far as we can see. She/Lexi will circle back with the merchants at their next TB. Ill follow up next week.

Thanks,
Adena

**Comment by c21hornak** [comment]
@AdenaG please add an update here.

**Comment by AdenaG** [comment]
Dept 92 still named J&R Express, but we cannot change the attributes in E1 until after Mi9 go live..
ON HOLD
Per IT:
Let’s stop and remember where we are…… We are still on Mi9 in the Existing Hierarchy. This is NOT changing until we go live on Mi9, the earliest would be at the end of Summer. (EP is an Exception)
There are a few reports that were created to accommodate the Planners who work in the “New” hierarchy in EP. We will NOT be changing any Hierarchy names in either (any) of these systems.  At the moment we will have to navigate through this knowing that we will have to operate in both worlds until we get onto Mi9, and the new hierarchy.

**Comment by c21hornak** [comment]
@AdenaG thanks. Closing this project then.
