### ISSUE TITLE
Confirmation that Message was Sent on Contact Page

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#16]
Elisabeth wants for customers to receive a visual confirmation with some text like “We’ve received your message and will respond as soon as possible.” after they click “SEND” to submit the form on the Contact Page.

https://www.c21stores.com/contact 
https://www.staging.c21.weblinc.com/contact 

Please setup a prototype in STAGING and show it to Elisabeth for any feedback/changes.

**Comment by juanmriosv** [comment]
@c21hornak 

Prototype on Staging (I followed the alert colors that weblinc has in place.
https://www.staging.c21.weblinc.com/contact

**Comment by c21hornak** [comment]
Sent request to Emily for copy via Workfront: https://c21.attask-ondemand.com/issue/view?ID=58daf68200638ab72438e45841a668ca

> **Copy Request for Web Production Project: Add a Confirmation Message on the Contact Us Page**
> 
> Request for copy for a confirmation message that displays on the Contact Us Page upon submitting the form.
> 
> View example here with placeholder text: https://www.staging.c21.weblinc.com/contact

**Comment by c21hornak** [comment]
@juanmriosv here is the Copy Doc to update the message copy.
https://docs.google.com/spreadsheets/d/1XgToq8SwFYM0xMPdpXb_PrckMQk7VbH-ZazbT4DAJtI/edit?ts=58dbe304#gid=1501240443

**Comment by juanmriosv** [comment]
@c21hornak 
Will do. Need access to [doc](https://docs.google.com/spreadsheets/d/1XgToq8SwFYM0xMPdpXb_PrckMQk7VbH-ZazbT4DAJtI/edit?ts=58dbe304#gid=1501240443)

**Comment by juanmriosv** [comment]
@c21hornak 
Done in Staging
![screen shot 2017-04-24 at 10 45 10 am](https://cloud.githubusercontent.com/assets/16789090/25342856/53f6d99e-28db-11e7-9789-53853c1df188.png)

**Comment by c21hornak** [comment]
Looks good. @AdenaG can you please QA this today?

**Comment by AdenaG** [comment]
@juanmriosv 
Pass in STAGING.

**Comment by juanmriosv** [comment]
@c21hornak 
Ok to push to production?

**Comment by c21hornak** [comment]
@juanmriosv yes

**Comment by juanmriosv** [comment]
@c21hornak 
Done, pushed to production

**Comment by AdenaG** [comment]
@juanmriosv @c21hornak 
I have to backtrack - FAIL in STAGING & PROD. The X to close out of the pop-up doesn't work, however the pop-up closes so quickly on its own, most people wouldn't even get there to close it in time. Ideally, should be removed if it doesnt work.

**Comment by AdenaG** [comment]
@juanmriosv 
Per our conversation that you are using the WL green alerts for this, I confirmed that the WL ones do close when you X out of them.

**Comment by c21hornak** [comment]
I don't think it's a big enough issue to take time to fix, considering other work on our plates right now. We can revisit if this starts to bother people/if people start reporting it as an issue. Closing.

**Comment by c21hornak** [comment]
@juanmriosv this might need to be pushed to PROD again - can you check pls?
