### ISSUE TITLE
PLCC Users: Add x More $ to Get Free Shipping Message in Cart

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#26]
Whereas https://github.com/Century21Stores/SPECIAL/issues/24 covers Acquisition Users, this ticket should enhance that feature to also include PLCC Card Holders.

**Consider the Free Shipping policy for PLCC Card Holders:**
Premier Credit Card Holders: they get free shipping if order subtotal is $50 or greater
Elite Credit Card Holders: they get free shipping on all orders

**NOTE:** Currently, we're actually giving Premier Credit Card Holders free shipping on all orders because we cannot programmatically make the real policy work until this WebLinc ticket is complete:
• [C21STATUS Premier Cardholders Free Shipping with $50 Order (C21-286)](https://jira.tools.weblinc.com/browse/C21-286)

**Final Experience:**

(final requirements TBD)

• Acquisition Users should continue seeing the calculation based on the subtotal needing to be $75 or greater
• Premier Credit Card Holders should see the calculation based on the subtotal needing to be $50 or greater
• Elite Credit Card Holders should not see any calculation.

**Comment by c21hornak** [comment]
@juanmriosv In order to be able to recognize Premier vs. Elite, can you use attributes data from `body[data-analytics] >> payload.user[0].profile` (see [this WebLinc ticket](https://jira.tools.weblinc.com/browse/C21-125)) to give Premier and Elite the required different experiences? If you think that will be possible we can add a requirement to that WebLinc ticket so they also expose the PLCC tier in the attributes of `body[data-analytics] >> payload.user[0].profile`.

**Comment by juanmriosv** [comment]
@c21hornak 
The only issue that I see with "payload.user[0].profile" is that returns many information about the customer, including Loyalty ID and phone number. If it is possible to expose just the "type customer" of customer( securely) via that method or other one; then, I can pull  that info and do what ever we need to do.

Also, As far as I understood Melissa, this functionality is for non PLCC users. Because PLCC gets free shipping any way

**Comment by c21hornak** [comment]
Closing this and we can continue the work on #24
