### ISSUE TITLE
Search Redirects for Customers Wanting to Check Gift Card Balances

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#28]
There is a Search Redirect already set up for “mystery gift card” to this MysteryGiftCards content page https://www.c21stores.com/pages/mysterygiftcards

Set up additional Search Redirects to the same page, for specific terms like “gift card balance”, “gift card balance check”, “how to check gift card balance”, “check gift card balance”, "how do i check my gift card balance online?”, which currently don’t redirect, they only return search results pages.

Use search report to find other search terms to set up redirects for.

**Comment by AdenaG** [comment]
@c21hornak 
Been asking for this since launch lol - done.
Will pull report for additional search terms related to content pages and redirect there.

**Comment by c21hornak** [comment]
Cache might not have cleared yet. Just checked this one and still see search results: https://www.c21stores.com/search?utf8=%E2%9C%93&q=Gift+card+balance+check

Ok to keep ticket with you until the additional terms are also done.

**Comment by AdenaG** [comment]
Hm, its redirecting to mysterygiftcards lp for me. Anything that includes the terms gift card balance should.

**Comment by AdenaG** [comment]
Pulled all non product-specific search terms YTD and created an additional redirect for anything that includes "track order" to pages/ordering-payment based on results. Asking Lisa to pull monthly when she pulls her other search data.

**Comment by AdenaG** [comment]
Moving the above comments unrelated to gift card balance to this ticket https://github.com/Century21Stores/SPECIAL/issues/39

**Comment by c21hornak** [comment]
I had to start a new session but it's working for me now.

**Comment by AdenaG** [comment]
Per Elisabeth's request, change 'gift card balance' redirect to here https://www.c21stores.com/contact.
Complete.
