### ISSUE TITLE
QA Process for Daily Quick Checks (TTI: 20 mins)

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#40]
Build and document a new process around early-morning (7AM) testing of essential site functionality. Target Time Investment for this kind of testing should be 20 minutes per morning.

The primary goal of this process is to find, before the start of the business day, any major site issues that may impact the daily morning emails that start going out at 8AM and to be able to inform decision-makers of the major site issues soon enough for them to delay the email send if they deem it necessary.

**Comment by AdenaG** [comment]
"Daily morning QA Quickcheck" to be done about 7:30-7:40am on weekdays.
https://docs.google.com/spreadsheets/d/1btgK8elwRTWAzxJNS4q9mWFBQ8yGznsdlL0fW0lzxNY/edit?usp=sharing

**Comment by c21hornak** [comment]
![daily-quick-check-process](https://cloud.githubusercontent.com/assets/19403001/25067227/d6754df6-220a-11e7-9779-182a822c12aa.png)
