### ISSUE TITLE
Update Reporting Process to Include Customer Service Search Terms

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#48]

**Comment by c21hornak** [comment]
@AdenaG I see the tab "Customer Service & Non Product/Brand SEARCHES" on the [2017 Dashboard](https://docs.google.com/spreadsheets/d/1SpfBRzd0zRbbe4mUY1Br56nrWtbe2EzKIOEzs82T14s/edit#gid=1625221873), but is this really all of them? I was anticipating a much longer list.

**Comment by AdenaG** [comment]
All of them are listed. Request was to remove a lot that we had back in CF.
