### ISSUE TITLE
SEO Project to Update Categories Title Tags & Meta Descriptions January 2017

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/SPECIAL#7]
Investigate the way we can improve[ this](https://docs.google.com/spreadsheets/d/11e9Fz-AkS_riqpLNoNucHxyBDzaVnIsiJ3x3FQ26bys/edit?usp=sharing) from our end.

**Comment by juanmriosv** [comment]
Done:

**- Email has been sent to Ali, regarding the _Related Product_ Section, asking if we are able to:**
(waiting for response)

1. Change the <h2> elements to <h3>, and what would be the impact
2. To make the values, from these elements, visible in google crawler. 

Currently we have this:
**Landing Pages:**
![screen shot 2017-01-26 at 10 01 25 am](https://cloud.githubusercontent.com/assets/16789090/22336358/faab7af4-e3af-11e6-80a7-3e66ad8bacb3.png)

**Category Pages**
![screen shot 2017-01-26 at 10 02 06 am](https://cloud.githubusercontent.com/assets/16789090/22336372/05a997e2-e3b0-11e6-9543-6d230a38ed68.png)

In the _Related Product_ section, Crawlers are Pulling:
![screen shot 2017-01-26 at 9 51 28 am](https://cloud.githubusercontent.com/assets/16789090/22336379/0c7ef936-e3b0-11e6-8bfc-8669a758c578.png)


**- Changing all elements (headers) should be done in the page template. <meta> tags can be added using a tag management tool, but it is recommended to do it as well in the actual page template**

**Comment by c21hornak** [comment]
This project turned out just to be to populate Title Tag and Meta Description from this Google Doc.
https://docs.google.com/spreadsheets/d/11e9Fz-AkS_riqpLNoNucHxyBDzaVnIsiJ3x3FQ26bys/edit#gid=0

**Comment by c21hornak** [comment]
Juan & Lydia completed this on 2/3/17. Closing.

**Comment by c21hornak** [comment]
Ken Mitchell shared positive results on 2/23/17.
![unknown](https://cloud.githubusercontent.com/assets/19403001/24779816/a6c50030-1b00-11e7-86fa-0d3f122423dc.jpeg)
