### ISSUE TITLE
Add Conditional Formatting to Promo Doc

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/SPECIAL#8]
This is to help, at a glance, identify **setup due dates,** **ending Promos,** and **notes.** In the "START DATE" and "END DATE" columns.

## **START DATE column:**
- Anything that is not a date will turn red
- Any date that falls in the next two weeks, will turn red
- Any wrong date, will turn red

Examples (base on Today: 1/26/2017):
![screen shot 2017-01-26 at 10 57 51 am](https://cloud.githubusercontent.com/assets/16789090/22339011/b4735d34-e3b6-11e6-99c2-7d2c6fc7363a.png)

## **END DATE column:**
- Anything that is not a date will turn red
- Any date that falls in "TOMORROW" from the date the doc is view, will turn black solid
- Any wrong date, will turn red

Examples (base on Today: 1/26/2017):
![screen shot 2017-01-26 at 11 02 57 am](https://cloud.githubusercontent.com/assets/16789090/22339305/7cdb1302-e3b7-11e6-80e3-d75bc11e4d1b.png)

**Comment by c21hornak** [comment]
From: "Rios, Juan Manuel" <jrios@c21stores.com>
Date: Monday, January 30, 2017 at 9:26 AM
To: "Goldis, Adena" <agoldis@c21stores.com>
Cc: Michael Hornak <mhornak@c21stores.com>
Subject: Re: Promo Doc

Hi Adena,

Agree. Let me see if it is possible with a formula.

Juan

————————————————————————————
From: "Goldis, Adena" <agoldis@c21stores.com>
Date: Monday, January 30, 2017 at 9:20 AM
To: Juan Rios <jrios@c21stores.com>
Cc: "Hornak, Michael" <mhornak@c21stores.com>
Subject: Re: Promo Doc

Hi Juan,
Your call, but re ‘ending tomorrow’ turning black, maybe you should leave it black until the end date is over, considering there are promos that end over the weekend and it may not be looked at on Sat and Sun. 
For example, these are ending today, so they were black yesterday only.

**Comment by AdenaG** [comment]
Adding this here that conditional formatting was also added for the following: 
A in active column turns the row green
T in active column turns the row yellow.

**Comment by c21hornak** [comment]
• Juan added conditional formatting to the Start/End Date Columns on 1/26.
• Adena added conditional formatting to the Active/Test (A/T) Columns

Closing.
