### ISSUE TITLE
LiveChat Front-End Customizations for Launch

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#96]
Desktop view is ok, but, please use custom code in the LiveChat admin to affect the mobile version of the LiveChat bar on STAGING. Some ideas we think can work are the following, but feel free to tweak these suggestions but better UX or come up with additional ones
• after page loads and chat bar hasn't been touched for a few seconds, shrink/squish/slide it down to appear shorter but so the user can still tell what it is.
• after page loads and chat bar hasn't been touched for a few seconds, the chat bar turns into a small circle/bubble 
• make the chat bar/bubble/circle draggable by the user

**Comment by c21hornak** [comment]
@juanmriosv this is a request from Elisabeth to please use the LiveChat custom code areas to manipulate the mobile version of the LiveChat bar so there will not be any UX issues with it. Adena & I briefly discussed and had the above ideas, which are flexible, and Elisabeth will choose which she likes best.

**Comment by juanmriosv** [comment]
@c21hornak 

Is the team from Live chat able to customize if required?

**Comment by c21hornak** [comment]
@juanmriosv I don't think they offer development services like that. You mean like if we don't have the time to do it?

**Comment by AdenaG** [comment]
@juanmriosv in case you were looking for it, they have a field to input CSS here:
![screen shot 2017-08-15 at 12 01 09 pm](https://user-images.githubusercontent.com/20344050/29324282-8f2d46a4-81b1-11e7-9777-f10294346463.png)

**Comment by juanmriosv** [comment]
@c21hornak, 
No I meant for things that we are not able to do. It is limited what I can do via their admin.
Also,
What you are suggesting above is based on the first time a user visit the page or re-visits.
The experience is different.

**Comment by c21hornak** [comment]
@juanmriosv ok understood. Do you think any manipulations might be possible with WebLinc admin or Justuno? I know neither extend their reach into the checkout, but LiveChat does, which i think would be a problem.

**Comment by juanmriosv** [comment]
@c21hornak 

I will test if any manipulations are visible to their iframe via the admin.
Seems that the ideas you describe above are for first time users. 
Once, the user comes back, the experiences changes (to a bubble avatar).

Also, opening the chat right when the page loads seems intrusive for small screens (specially on mobile). As far as I know, the only way not to have the chat automatically open, is to delete the greeting message, but it is not conditioned to the device. So, we can not choose to have it open on desktop but not on mobile. Unless we create two separate groups/ URL rules. One for mobile, one for desktop.

Is this visible?

Chat room can be customized for different pages (https://www.livechatinc.com/kb/setting-up-url-rules-for-groups/)

**Comment by AdenaG** [comment]
@juanmriosv. Greeting messages and URL rules are 2 different things, but greeting messages can have additional rules set up with custom variables that may account for if a user is on mobile or desktop: https://www.livechatinc.com/kb/custom-variables-configuration/?utm_source=webapp&utm_medium=link&utm_campaign=webapp_knowledge_base

The bar and bubble avatars are set globally, but I was seeing that something wasnt caching properly, which may be why you are seeing the experience change.

**Comment by juanmriosv** [comment]
It does not seem to be that way @AdenaG.
I've just chatted with customer support from LiveChat and they stated this:
![screen shot 2017-08-15 at 1 00 20 pm](https://user-images.githubusercontent.com/16789090/29326496-baade1dc-81b9-11e7-8c41-92f5b6fae83d.png)
From her answer, there are two different experiences. Was this looked into?


Also, Greeting messages and URL rules are two different things; I am only saying that you can customized the chat using URL rules, and turning off the "expand chat" feature by deleting the greeting messages.

**Comment by AdenaG** [comment]
@juanmriosv this might be better to go over in person as chat bubble and avatar are different as well, but I think we are on the same page.

What do you mean by 'expand chat feature'? If we delete the greeting messages, there is no prompting customers to chat, all chat would have to be triggered by them, which is not what Elisabeth wanted.

**Comment by juanmriosv** [comment]
@c21hornak @AdenaG 
Where can I read about the requirements from Elisabeth?

**Comment by AdenaG** [comment]
@juanmriosv 
https://docs.google.com/spreadsheets/d/1V0KSSBiDXqXxY_B7s0DELt2yxn-0gFTYky7fivi4xRM/edit?usp=sharing

**Comment by juanmriosv** [comment]
Thank you @AdenaG 

This is more a guide of what you are doing and the feature / implementation.
Is there anything listing the requirements from Elisabeth about the chat "expanding on loading" of the chat window?

Also, Column "C" states different experience / messages based on pages visits and page URLs
is this final or still in progress?

**Comment by juanmriosv** [comment]
@c21hornak 
Let's go back a little bit.
What is it that we are trying to solve with this request?

**Comment by AdenaG** [comment]
sorry for delay. @juanmriosv re your above comment, there aren't requirements from Elisabeth about the chat "expanding on loading" of the chat window because that is default functionality when we engage a customer in chat. She wanted to keep within the default functionality as much as possible without having to customize. These are the 'chat engagements' referred to in column C. They have changed since the original and may be subject to change going forward. You can see the current ones here: https://my.livechatinc.com/settings/greetings

**Comment by c21hornak** [comment]
@AdenaG I believe we can close this now, do you agree? I know Elisabeth wants some customization for how LiveChat currently looks on mobile, but I feel like that's a separate request from this.

**Comment by AdenaG** [comment]
@c21hornak 
We can open new ticket if you want. Both relate to customizing the view on Livechat mobile, but slightly different customizations.

**Comment by c21hornak** [comment]
Closing.
